name: Cleanup

on:
  repository_dispatch:
    types: ['Delete old workflow runs']

jobs:
  cleanup:
    name: Delete old workflow runs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 15
